[workspace.package]
version = "0.0.7"
authors = ["Gear Technologies"]
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/gear-tech/sails"

[workspace]
resolver = "2"
members = ["dd-lib", "hello"]

[workspace.dependencies]
dd-lib = { path = "dd-lib" }
