name: Release (Rust)

on:
  push:
    tags:
      - 'rs/v*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract Release Version
        id: extract_release_version
        run: |
          RELEASE_TAG=${GITHUB_REF#refs/tags/}
          RELEASE_VERSION=${RELEASE_TAG#rs/v}
          if [[ ! $RELEASE_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "'$VERSION' is not a valid semver version"
            exit 1
          fi
          echo "Release Version: $RELEASE_VERSION"
          echo "::set-output name=release_version::$RELEASE_VERSION"

      - name: Say Hi
        run: |
          echo "Hello, World!"
          echo "We are about to release: ${{ steps.extract_release_version.outputs.release_version }}"
