name: Release (Rust)

on:
  release:
    types: [published]

jobs:
  j1:
    if: startsWith(github.ref, 'refs/tags/rs/v')
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Say Hi
        run: echo "Hello, World!"
