name: Release (Rust)

on:
#   release:
#     types: [published]
    push:
        tags:
        - 'rs/v*'

jobs:
  j1:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Say Hi
        run: |
          echo "Hello, World!"
          RELEASE_TAG=${GITHUB_REF#refs/tags/}
          echo "RELEASE_TAG: $RELEASE_TAG"
